services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/opt/StarBurger:delegated
      - static_volume:/opt/StarBurger/staticfiles
      - media_volume:/opt/StarBurger/media
      - frontend_bundles:/opt/StarBurger/bundles
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - YANDEX_GEOCODER_API_KEY=${YANDEX_GEOCODER_API_KEY}
    depends_on:
      - db
    command: python -m gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_bundles:/app/bundles
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=info
    depends_on:
      - backend
    ports:
      - "1234:1234"
    command: npm start
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/html/staticfiles:ro
      - media_volume:/var/www/html/media:ro
      - frontend_bundles:/var/www/html/bundles:ro
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  media_volume:
  static_volume:
  frontend_bundles: 