version: '3.8'

name: star-burger

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: star-burger-backend
    volumes:
      - ./backend:/opt/StarBurgerDockerizations:delegated
      - static_volume:/opt/StarBurgerDockerizations/staticfiles
      - media_volume:/opt/StarBurgerDockerizations/media
      - frontend_bundles:/opt/StarBurgerDockerizations/bundles
    environment:
      - DATABASE_URL=postgres://starburger_user:0704@localhost:5432/starburger_prod
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - YANDEX_GEOCODER_API_KEY=${YANDEX_GEOCODER_API_KEY}
    network_mode: "host"
    command: python -m gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: star-burger-frontend
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - frontend_bundles:/usr/share/nginx/html/bundles
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  media_volume:
  static_volume:
  frontend_bundles: 