# Generated by Django 5.1.6 on 2025-04-16 18:25

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("restaurant", "Передан в ресторан"),
                            ("delivery", "У курьера"),
                            ("completed", "Завершён"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("electronic", "Электронно"), ("cash", "Наличные")],
                        db_index=True,
                        default="cash",
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о заказе",
                        verbose_name="Комментарий",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("firstname", models.CharField(max_length=50, verbose_name="Имя")),
                ("lastname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="RU", verbose_name="Номер телефона"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата звонка"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="цена",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="картинка")),
                (
                    "special_status",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="спец.предложение"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="описание"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Доступен для заказа"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("electronic", "Электронно"), ("cash", "Наличные")],
                        db_index=True,
                        default="cash",
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                (
                    "address",
                    models.CharField(blank=True, max_length=100, verbose_name="адрес"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="контактный телефон"
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ресторан",
                "verbose_name_plural": "рестораны",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="количество",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="фиксированная цена",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="foodcartapp.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="foodcartapp.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "элемент заказа",
                "verbose_name_plural": "элементы заказа",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="foodcartapp.productcategory",
                verbose_name="категория",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="foodcartapp.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="foodcartapp.restaurant",
                verbose_name="Исполняющий ресторан",
            ),
        ),
        migrations.CreateModel(
            name="RestaurantMenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "availability",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="в продаже"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="foodcartapp.product",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="foodcartapp.restaurant",
                        verbose_name="ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "пункт меню ресторана",
                "verbose_name_plural": "пункты меню ресторана",
                "unique_together": {("restaurant", "product")},
            },
        ),
    ]
