# Generated by Django 5.1.6 on 2025-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        max_length=200, unique=True, verbose_name="Адрес места"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Широта"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Долгота"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Дата/время обновления",
                    ),
                ),
            ],
            options={
                "verbose_name": "координаты адреса",
                "verbose_name_plural": "координаты адресов",
                "indexes": [
                    models.Index(
                        fields=["address"], name="geocoder_ad_address_1f6f8c_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="geocoder_ad_updated_5020cd_idx"
                    ),
                ],
            },
        ),
    ]
